-- https://school.programmers.co.kr/learn/courses/30/lessons/59043
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
from ANIMAL_INS, ANIMAL_OUTS
where ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID and ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME