-- https://school.programmers.co.kr/learn/courses/30/lessons/59043
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
from ANIMAL_INS, ANIMAL_OUTS
where ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID and ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME

-- https://school.programmers.co.kr/learn/courses/30/lessons/131533
SELECT a.PRODUCT_CODE, sum(a.PRICE*b.SALES_AMOUNT) as SALES
from PRODUCT a, OFFLINE_SALE b
where a.PRODUCT_ID = b.PRODUCT_ID
group by PRODUCT_CODE
ORDER BY sales DESC, a.product_code